#!/bin/sh
# Avoid committing all of the data to the repository.

LOCAL=$1
S3=$2

set -e

echo Copying data to S3
for century in 18 19 20
  do
  for decade in `seq 0 9`
    do
    echo Copying the $century${decade}0s
    cp -R $LOCAL/www/output/$century$decade* $S3
#   cp $LOCAL/data/people/$century$decade*.json $S3/data/people
  done
done
