#!/bin/sh
# Avoid committing all of the data to the repository.

set -e

# Update
git pull

tmp=$(mktemp -d)
cp -R www $tmp

# Generate yaml templates

# Compile
(
  cd $tmp/www
  nanoc compile
)

# Copy data over
cp data/people/*.json $tmp/www/output/data/people

# Mount S3
mkdir $tmp/s3
s3fs -o use-rss=1 www.deadpeoplebornonmybirthday.com $tmp/s3
cp -R $tmp/www/output/* $tmp/s3
sudo umount $tmp/s3
