#!/bin/sh
# Avoid committing all of the data to the repository.

set -e

# Update
git pull

tmp=$(mktemp -d)
cp -R www $tmp

echo Compiling site
(
  cd $tmp/www
  nanoc compile > /dev/null
)

echo Generating birthday pages
bin/write_birthday_yaml.py $tmp/www/output

# Mount S3
mkdir $tmp/s3
s3fs -o use_rrs=1 www.deadpeoplebornonmybirthday.com $tmp/s3

echo Copying interface and data to S3
for century in 18 19 20
  do
  for decade in `seq 0 9`
    do
    cp $tmp/www/output/$century$decade*.json $tmp/s3
    cp data/people/$century$decade*.json $tmp/s3/data/people
  done
done

echo umounting S3
sudo umount $tmp/s3
